name: mood_pop
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0

  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  image: ^4.1.0
  flutter_sound: ^9.2.13
  audioplayers: ^5.1.0
  assets_audio_player: ^3.1.1
  permission_handler: ^11.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  badges: ^3.1.2
  shimmer: ^3.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets: 
  - assets/icons/
  - assets/logos/
  - assets/Empty/
